one-line:
    path: "tooltips:tooltips/default/one-line.png"
    height: 10
    padding: 1
    lines: 1
    ascents:
        theme-ascent: 0
        text-start-ascent: -3
        text-line-spacing: 5
two-line:
    path: "tooltips:tooltips/default/two-line.png"
    height: 13
    padding: 1
    lines: 2
    ascents:
        theme-ascent: 0
        text-start-ascent: -2
        text-line-spacing: 5
three-line:
    path: "tooltips:tooltips/default/three-line.png"
    height: 18
    padding: 1
    lines: 3
    ascents:
        theme-ascent: 0
        text-start-ascent: -2
        text-line-spacing: 5
four-line:
    path: "tooltips:tooltips/default/four-line.png"
    height: 23
    padding: 1
    lines: 4
    ascents:
        theme-ascent: 0
        text-start-ascent: -2
        text-line-spacing: 5
five-line:
    path: "tooltips:tooltips/default/five-line.png"
    height: 28
    padding: 1
    lines: 5
    ascents:
        theme-ascent: 0
        text-start-ascent: -2
        text-line-spacing: 5