name: Tooltips
main: fi.septicuss.tooltips.Tooltips
version: ${project.version}
api-version: 1.16

author: Septicuss

softdepend: [ PlaceholderAPI, ItemsAdder, Oraxen, WorldGuard, WorldEdit, MythicCrucible, MythicMobs, Citizens, ProtocolLib, packetevents ]

libraries:
   - net.kyori:adventure-text-minimessage:${adventure.core.version}
   - net.kyori:adventure-text-serializer-plain:${adventure.core.version}
   - net.kyori:adventure-platform-bukkit:${adventure.platform.version}

commands:
   tooltips:
      aliases: [tooltip, tt]