name: Tooltips
main: fi.septicuss.tooltips.Tooltips
version: 2.3
api-version: 1.16

author: Septicuss

softdepend: [ PlaceholderAPI, ItemsAdder, Nexo, Oraxen, WorldGuard, WorldEdit, MythicCrucible, MythicMobs, Citizens, ProtocolLib, packetevents, BetonQuest ]

commands:
   tooltips:
      aliases: [tooltip, tt]